# Generated by Django 4.1.3 on 2022-12-05 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('rut', models.CharField(max_length=20)),
                ('edad', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=15)),
                ('SegundoApoderado', models.CharField(max_length=40)),
                ('telefono2', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('edad', models.CharField(max_length=40)),
                ('curso_asignado', models.CharField(max_length=20)),
                ('fechaInicio', models.DateField(max_length=40)),
                ('fechatermino', models.DateField(max_length=10)),
                ('saldo', models.CharField(max_length=40)),
                ('rut', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('rut', models.CharField(max_length=20)),
                ('edad', models.CharField(max_length=40)),
                ('curso', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=40)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templatesApp.apoderado')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templatesApp.profesor')),
            ],
        ),
    ]
